name: master
on:
  push:
    branches:
      - master
permissions: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: '^1.21'
          check-latest: true
      - run: go version
      - run: go vet ./github ./google ./zalando
      - run: go test ./...
      - run: go test -race ./...
