name: master
on:
  push:
    branches:
      - master
permissions: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: '^1.21'
          check-latest: true
      - run: go version
      - run: go vet ./github ./google ./zalando
      - run: go test ./...
      - run: go test -race ./...
